packages:
  - artifacts/*
  - lib/*
  - scripts

autoInstallPeers: false

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - msw

overrides:
  path-to-regexp: 8.4.0
  picomatch@2: 2.3.2
  picomatch@4: 4.0.4
